version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: uniqlow19/diplom_backend
    env_file: .env
    restart: always
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db
  nginx:
    image: uniqlow19/diplom_nginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media