# Generated by Django 3.2 on 2024-04-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Параметр')),
                ('slug', models.SlugField(max_length=254, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=254, verbose_name='Стиль')),
                ('value', models.CharField(max_length=254, verbose_name='Значение')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='reports.param', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
