# Generated by Django 3.2 on 2024-04-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_param_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('slug', models.SlugField(max_length=254, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.AlterField(
            model_name='param',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='reports.style', verbose_name='Стиль'),
        ),
    ]
